Xenomai: Clocks and timers services.
Clocks and timers services.
Clocks and timers services.
Functions
static int do_clock_host_realtime (struct timespec *tp)
Read the host-synchronised realtime clock.
static int timer_create (clockid_t clockid, const struct sigevent *__restrict__ evp, timer_t *__restrict__ timerid)
Create a timer object.
static int timer_settime (timer_t timerid, int flags, const struct itimerspec *__restrict__ value, struct itimerspec *__restrict__ ovalue)
Start or stop a timer.
static int timer_gettime (timer_t timerid, struct itimerspec *value)
Get timer next expiration date and reload value.
Detailed Description
Clocks and timers services.
Xenomai POSIX skin supports two clocks:
CLOCK_REALTIME maps to the nucleus system clock, keeping time as the amount of time since the Epoch, with a resolution of one nanosecond.
CLOCK_MONOTONIC maps to an architecture-dependent high resolution counter, so is suitable for measuring short time intervals. However, when used for sleeping (with clock_nanosleep()), the CLOCK_MONOTONIC clock has a resolution of one nanosecond, like the CLOCK_REALTIME clock.
CLOCK_MONOTONIC_RAW is Linux-specific, and provides monotonic time values from a hardware timer which is not adjusted by NTP. This is strictly equivalent to CLOCK_MONOTONIC with Xenomai, which is not NTP adjusted either.
Timer objects may be created with the timer_create() service using either of the two clocks. The resolution of these timers is one nanosecond, as is the case for clock_nanosleep().
See also:
Specification.
Function Documentation
static int do_clock_host_realtime (struct timespec * tp) [static]
Read the host-synchronised realtime clock.
Obtain the current time with NTP corrections from the Linux domain
Parameters:
tp pointer to a struct timespec
Return values:
0 on success;
-1 if no suitable NTP-corrected clocksource is availabel
See also:
Specification.
static int timer_create (clockid_t clockid, const struct sigevent *__restrict__ evp, timer_t *__restrict__ timerid) [inline, static]
Create a timer object.
This service creates a time object using the clock clockid.
If evp is not NULL, it describes the notification mechanism used on timer expiration. Only notification via signal delivery is supported (member sigev_notify of evp set to SIGEV_SIGNAL). The signal will be sent to the thread starting the timer with the timer_settime() service. If evp is NULL, the SIGALRM signal will be used.
Note that signals sent to user-space threads will cause them to switch to secondary mode.
If this service succeeds, an identifier for the created timer is returned at the address timerid. The timer is unarmed until started with the timer_settime() service.
Parameters:
clockid clock used as a timing base;
evp description of the asynchronous notification to occur when the timer expires;
timerid address where the identifier of the created timer will be stored on success.
Return values:
0 on success;
-1 with errno set if:
EINVAL, the clock clockid is invalid;
EINVAL, the member sigev_notify of the sigevent structure at the address evp is not SIGEV_SIGNAL;
EINVAL, the member sigev_signo of the sigevent structure is an invalid signal number;
EAGAIN, the maximum number of timers was exceeded, recompile with a larger value.
See also:
Specification.
References sem_getvalue(), and xntimer_init().
static int timer_gettime (timer_t timerid, struct itimerspec * value) [inline, static]
Get timer next expiration date and reload value.
This service stores, at the address value, the expiration date (member it_value) and reload value (member it_interval) of the timer timerid. The values are returned as time intervals, and as multiples of the system clock tick duration (see note in section Clocks and timers services for details on the duration of the system clock tick). If the timer was not started, the returned members it_value and it_interval of value are zero.
Parameters:
timerid timer identifier;
value address where the timer expiration date and reload value are stored on success.
Return values:
0 on success;
-1 with errno set if:
EINVAL, timerid is invalid;
EPERM, the timer timerid does not belong to the current process.
See also:
Specification.
static int timer_settime (timer_t timerid, int flags, const struct itimerspec *__restrict__ value, struct itimerspec *__restrict__ ovalue) [inline, static]
Start or stop a timer.
This service sets a timer expiration date and reload value of the timer timerid. If ovalue is not NULL, the current expiration date and reload value are stored at the address ovalue as with timer_gettime().
If the member it_value of the itimerspec structure at value is zero, the timer is stopped, otherwise the timer is started. If the member it_interval is not zero, the timer is periodic. The current thread must be a POSIX skin thread (created with pthread_create()) and will be notified via signal of timer expirations. Note that these notifications will cause user-space threads to switch to secondary mode.
When starting the timer, if flags is TIMER_ABSTIME, the expiration value is interpreted as an absolute date of the clock passed to the timer_create() service. Otherwise, the expiration value is interpreted as a time interval.
Expiration date and reload value are rounded to an integer count of nanoseconds.
Parameters:
timerid identifier of the timer to be started or stopped;
flags one of 0 or TIMER_ABSTIME;
value address where the specified timer expiration date and reload value are read;
ovalue address where the specified timer previous expiration date and reload value are stored if not NULL.
Return values:
0 on success;
-1 with errno set if:
EPERM, the caller context is invalid;
EINVAL, the specified timer identifier, expiration date or reload value is invalid;
EPERM, the timer timerid does not belong to the current process.
Valid contexts:
Xenomai kernel-space POSIX skin thread,
kernel-space thread cancellation cleanup routine,
Xenomai POSIX skin user-space thread (switches to primary mode),
user-space thread cancellation cleanup routine.
See also:
Specification.
References xntimer_start(), and xntimer_stop().