Xenomai: Threads management services.
Threads management services.
Threads management services.
Modules
Thread cancellation.
Thread cancellation.
Functions
static int pthread_getschedparam (pthread_t tid, int *pol, struct sched_param *par)
Get the scheduling policy and parameters of the specified thread.
static int pthread_getschedparam_ex (pthread_t tid, int *pol, struct sched_param_ex *par)
Get the extended scheduling policy and parameters of the specified thread.
static int pthread_create (pthread_t *tid, const pthread_attr_t *attr)
Create a thread.
static int pthread_make_periodic_np (pthread_t thread, clockid_t clock_id, struct timespec *starttp, struct timespec *periodtp)
Make a thread periodic.
static int pthread_set_mode_np (int clrmask, int setmask, int *mode_r)
Set the mode of the current thread.
static int pthread_set_name_np (pthread_t thread, const char *name)
Set a thread name.
static int pthread_setschedparam (pthread_t tid, int pol, const struct sched_param *par)
Set the scheduling policy and parameters of the specified thread.
static int pthread_setschedparam_ex (pthread_t tid, int pol, const struct sched_param_ex *par)
Set the extended scheduling policy and parameters of the specified thread.
Detailed Description
Threads management services.
See also:
Specification.
Function Documentation
static int pthread_create (pthread_t * tid, const pthread_attr_t * attr) [inline, static]
Create a thread.
This service creates a Cobalt thread control block. The created thread may use Cobalt API services.
The new thread control block can be mapped over a regular Linux thread, forming a Xenomai shadow.
The new thread signal mask is inherited from the current thread, if it was also created with pthread_create(), otherwise the new thread signal mask is empty.
Other attributes of the new thread depend on the attr argument. If attr is null, default values for these attributes are used.
Returning from the start routine has the same effect as calling pthread_exit() with the return value.
Parameters:
tid address where the identifier of the new thread will be stored on success;
attr thread attributes;
Returns:
0 on success;
an error number if:
EINVAL, attr is invalid;
EAGAIN, insufficient memory exists in the system heap to create a new thread, increase CONFIG_XENO_OPT_SYS_HEAPSZ;
EINVAL, thread attribute inheritsched is set to PTHREAD_INHERIT_SCHED and the calling thread does not belong to the POSIX skin;
See also:
Specification.
Note:
When creating or shadowing a Xenomai thread for the first time in user-space, Xenomai installs a handler for the SIGWINCH signal. If you had installed a handler before that, it will be automatically called by Xenomai for SIGWINCH signals that it has not sent.
If, however, you install a signal handler for SIGWINCH after creating or shadowing the first Xenomai thread, you have to explicitly call the function xeno_sigwinch_handler at the beginning of your signal handler, using its return to know if the signal was in fact an internal signal of Xenomai (in which case it returns 1), or if you should handle the signal (in which case it returns 0). xeno_sigwinch_handler prototype is:
int xeno_sigwinch_handler(int sig, siginfo_t *si, void *ctxt);
Which means that you should register your handler with sigaction, using the SA_SIGINFO flag, and pass all the arguments you received to xeno_sigwinch_handler.
References pthread_getschedparam_ex(), xnpod_init_thread(), xnpod_set_thread_tslice(), and xnsynch_init().
static int pthread_getschedparam (pthread_t tid, int * pol, struct sched_param * par) [inline, static]
Get the scheduling policy and parameters of the specified thread.
This service returns, at the addresses pol and par, the current scheduling policy and scheduling parameters (i.e. priority) of the Xenomai POSIX skin thread tid. If this service is called from user-space and tid is not the identifier of a Xenomai POSIX skin thread, this service fallback to Linux regular pthread_getschedparam service.
Parameters:
tid target thread;
pol address where the scheduling policy of tid is stored on success;
par address where the scheduling parameters of tid is stored on success.
Returns:
0 on success;
an error number if:
ESRCH, tid is invalid.
See also:
Specification.
static int pthread_getschedparam_ex (pthread_t tid, int * pol, struct sched_param_ex * par) [inline, static]
Get the extended scheduling policy and parameters of the specified thread.
This service is an extended version of pthread_getschedparam(), that also supports Xenomai-specific or additional POSIX scheduling policies, which are not available with the host Linux environment.
Typically, SCHED_SPORADIC parameters can be retrieved from this call.
Parameters:
tid target thread;
pol address where the scheduling policy of tid is stored on success;
par address where the scheduling parameters of tid is stored on success.
Returns:
0 on success;
an error number if:
ESRCH, tid is invalid.
See also:
Specification.
References XNRRB.
Referenced by pthread_create().
static int pthread_make_periodic_np (pthread_t thread, clockid_t clock_id, struct timespec * starttp, struct timespec * periodtp) [inline, static]
Make a thread periodic.
This service make the POSIX skin thread thread periodic.
This service is a non-portable extension of the POSIX interface.
Parameters:
thread thread identifier. This thread is immediately delayed until the first periodic release point is reached.
clock_id clock identifier, either CLOCK_REALTIME, CLOCK_MONOTONIC or CLOCK_MONOTONIC_RAW.
starttp start time, expressed as an absolute value of the clock clock_id. The affected thread will be delayed until this point is reached.
periodtp period, expressed as a time interval.
Returns:
0 on success;
an error number if:
ESRCH, thread is invalid;
ETIMEDOUT, the start time has already passed.
ENOTSUP, the specified clock is unsupported;
Rescheduling: always, until the starttp start time has been reached.
References xnpod_set_thread_periodic().
static int pthread_set_mode_np (int clrmask, int setmask, int * mode_r) [inline, static]
Set the mode of the current thread.
This service sets the mode of the calling thread. clrmask and setmask are two bit masks which are respectively cleared and set in the calling thread status. They are a bitwise OR of the following values:
PTHREAD_LOCK_SCHED, when set, locks the scheduler, which prevents the current thread from being switched out until the scheduler is unlocked;
PTHREAD_WARNSW, when set, causes the signal SIGXCPU to be sent to the current thread, whenever it involontary switches to secondary mode;
PTHREAD_CONFORMING can be passed in setmask to switch the current user-space task to its preferred runtime mode. The only meaningful use of this switch is to force a real-time shadow back to primary mode. Any other use either cause to a nop, or an error.
PTHREAD_LOCK_SCHED is valid for any Xenomai thread, the other bits are only valid for Xenomai user-space threads.
This service is a non-portable extension of the POSIX interface.
Parameters:
clrmask set of bits to be cleared;
setmask set of bits to be set.
mode_r If non-NULL, mode_r must be a pointer to a memory location which will be written upon success with the previous set of active mode bits. If NULL, the previous set of active mode bits will not be returned.
Returns:
0 on success;
an error number if:
EINVAL, some bit in clrmask or setmask is invalid.
References XNLOCK, xnpod_schedule(), xnpod_set_thread_mode(), and XNSHADOW.
static int pthread_set_name_np (pthread_t thread, const char * name) [inline, static]
Set a thread name.
This service set to name, the name of thread. This name is used for displaying information in /proc/xenomai/sched.
This service is a non-portable extension of the POSIX interface.
Parameters:
thread target thread;
name name of the thread.
Returns:
0 on success;
an error number if:
ESRCH, thread is invalid.
static int pthread_setschedparam (pthread_t tid, int pol, const struct sched_param * par) [inline, static]
Set the scheduling policy and parameters of the specified thread.
This service set the scheduling policy of the Xenomai POSIX skin thread tid to the value pol, and its scheduling parameters (i.e. its priority) to the value pointed to by par.
When used in user-space, passing the current thread ID as tid argument, this service turns the current thread into a Xenomai POSIX skin thread. If tid is neither the identifier of the current thread nor the identifier of a Xenomai POSIX skin thread this service falls back to the regular pthread_setschedparam() service, hereby causing the current thread to switch to secondary mode if it is Xenomai thread.
Parameters:
tid target thread;
pol scheduling policy, one of SCHED_FIFO, SCHED_COBALT, SCHED_RR or SCHED_OTHER;
par scheduling parameters address.
Returns:
0 on success;
an error number if:
ESRCH, tid is invalid;
EINVAL, pol or par->sched_priority is invalid;
EAGAIN, in user-space, insufficient memory exists in the system heap, increase CONFIG_XENO_OPT_SYS_HEAPSZ;
EFAULT, in user-space, par is an invalid address;
EPERM, in user-space, the calling process does not have superuser permissions.
See also:
Specification.
Note:
When creating or shadowing a Xenomai thread for the first time in user-space, Xenomai installs a handler for the SIGWINCH signal. If you had installed a handler before that, it will be automatically called by Xenomai for SIGWINCH signals that it has not sent.
If, however, you install a signal handler for SIGWINCH after creating or shadowing the first Xenomai thread, you have to explicitly call the function xeno_sigwinch_handler at the beginning of your signal handler, using its return to know if the signal was in fact an internal signal of Xenomai (in which case it returns 1), or if you should handle the signal (in which case it returns 0). xeno_sigwinch_handler prototype is:
int xeno_sigwinch_handler(int sig, siginfo_t *si, void *ctxt);
Which means that you should register your handler with sigaction, using the SA_SIGINFO flag, and pass all the arguments you received to xeno_sigwinch_handler.
References xnpod_schedule(), xnpod_set_thread_schedparam(), and xnpod_set_thread_tslice().
Referenced by pthread_setschedparam_ex().
static int pthread_setschedparam_ex (pthread_t tid, int pol, const struct sched_param_ex * par) [inline, static]
Set the extended scheduling policy and parameters of the specified thread.
This service is an extended version of pthread_setschedparam(), that supports Xenomai-specific or additional scheduling policies, which are not available with the host Linux environment.
Typically, a Xenomai thread policy can be set to SCHED_SPORADIC using this call.
Parameters:
tid target thread;
pol address where the scheduling policy of tid is stored on success;
par address where the scheduling parameters of tid is stored on success.
Returns:
0 on success;
an error number if:
ESRCH, tid is invalid.
EINVAL, par contains invalid parameters.
ENOMEM, lack of memory to perform the operation.
See also:
Specification.
References pthread_setschedparam(), xnpod_schedule(), xnpod_set_thread_schedparam(), and xnpod_set_thread_tslice().