
ccflags-y := -D__IN_XENOMAI__ -Iinclude/xenomai -Iinclude/xenomai/cobalt -Idrivers/xenomai/analogy

obj-$(CONFIG_XENO_DRIVERS_ANALOGY_FAKE) += analogy_fake.o

analogy_fake-y := fake.o

analogy_loop-y := loop.o
