Running applications with Xenomai 3.x
=====================================

Running a Xenomai 3 application
-------------------------------

For _Cobalt_, you will need the real-time core built into the target
Linux kernel as described in link:installing-xenomai-3-x[this
document].

For _Mercury_, you need no Xenomai-specific kernel support so far,
beyond what your host Linux kernel already provides. Your kernel
should at least provide high resolution timer support
(+CONFIG_HIGH_RES_TIMERS+), and likely complete preemption
(_PREEMPT_RT_) if your application requires short and bounded
latencies.

An application recognises a set of options that may be passed on the
command line, namely:

[horizontal]
*--<api>-clock-resolution=<ns>*::

	The clock resolution available with the real-time API, given
	as a count of nano-seconds, i.e. HZ=(1000000000 / ns).

[normal]
	<api> is the name of one of the existing Xenomai APIs your
	application can be linked against, e.g. _psos_, _vxworks_ or
	_alchemy_. When your application combines multiple APIs, you
	may pass several clock-resolution switches to set them all.

[normal]
	The default value depends on the API being considered. For
	instance, the VxWorks (TM) and pSOS (TM) emulators default to
	1 millisecond clock rates. The Alchemy API is tickless by
	default, i.e. +--alchemy-clock-resolution=1+.

CAUTION: Specifying a resolution greater than 1 nanosecond requires
the low resolution clock support to be available from the Xenomai
libraries (see the +--enable-lores-clock+
link:installing-xenomai-3-x[configuration switch]).

*--mem-pool-size=<kb>*::

	The initial size in Kilobytes of the main memory pool. This
	option only makes sense when the TLSF allocator is being used
	(i.e. +--enable-debug+ is not specified when compiling the
	Xenomai libraries). This is only a hint, since TLSF will
	increase the main pool size dynamically as needed, if needed.

[normal]
	However, this option may be used to pre-allocate the specified
	amount of memory to the application process, thus avoiding
	costly system calls to extend the data segment of such process
	while operating in time critical mode.

*--no-mlock*::

	Tells the Xenomai libraries not to lock the process memory
	while initializing. The application will have to handle this
	task when and how it sees fit, in order to avoid the extra
	latency induced by virtual memory paging.  Otherwise,
	`mlockall(MCL_CURRENT | MCL_FUTURE)` is automatically invoked
	as part of the API initialization duties.

[normal]
	This flag only applies to the _Mercury_ core. Memory must be
	locked when invoking dual kernel services, therefore this
	switch is a nop over _Cobalt_.

*--registry-root=<path>*::

	Tells Xenomai to root the object registry at the given path,
	instead of +/var/run/xenomai+ by default (see the
	+--enable-registry+ switch from the configuration options).

*--shared-registry*::

	Exports the registry of the process to other users. If access
	is possible, also depends on permissions of the registry path.
	By default, the registry is only accessible for the user that
	started the Xenomai process.

*--no-registry*::

	This switch disables registry support at runtime. No real-time
	objects will be exported to +/var/run/xenomai+, despite the
	registry code was compiled in.

*--no-sanity*::
*--sanity*::

	Turns off/on the sanity checks performed at application
	startup by the Xenomai libraries. This option overrides the
	--enable/disable-sanity options passed on the configuration
	line when building the Xenomai libraries.

[TIP]
	Passing *--no-sanity* allows running Xenomai libraries built
	for a single-processor system (i.e. --disable-smp) on a SMP
	system, assuming your application properly pins all threads
	to a single CPU.

*--session=<label>*::

	Name of the session the new process will be part of (or create
	if not present). If +--enable-pshared+ was given when
	configuring the Xenomai libraries, this label allows multiple
	processes giving the same label at startup to operate on the
	same set of objects.

[normal]
	For instance, a process can post a semaphore created by
	another process from the same session. This is done using a
	common heap area, shared by all processes within the same
	session.

[normal]
	This label is also used to form the registry mount point for
	each process, e.g. +/var/run/xenomai/<user>/<session>/<pid>+.
	See +--enable-registry+ from the build options.

[normal]
	By default, `anon@<pid>` is used as the session label, with <pid>
	equal to the system identifier of the process.

*--reset*::

	Forces removal of an older session. This only works if the
	process which initiated the former session has exited,
	otherwise an error is raised.

*--cpu-affinity=<cpu[,cpu]...>*::

	Sets the CPU affinity of threads created by the Xenomai
	libraries within the new process.

*--version*::

	Writes the Xenomai version information to stdout. The program
	immediately exits with a success code afterwards.

*--dump-config*::

	Dumps the configuration settings to stdout. Those settings are
	defined as a result of running the configure script. The
	program immediately exits with a success code afterwards.

Valgrind support
----------------

Running Xenomai applications over _Valgrind_ is currently available to
the _Mercury_ core only.

When the Valgrind API is available to the application process, the
configuration symbol CONFIG_XENO_VALGRIND_API is defined at build
time, and may be tested for existence by the application code. See the
tool documentation at
http://valgrind.org/docs/manual/manual-core-adv.html#manual-core-adv.clientreq/[this address].

The Xenomai autoconf script will detect the Valgrind core header on
the build system automatically, and define this symbol accordingly
(i.e. /usr/include/valgrind/valgrind.h).

[NOTE]
You may need to install the Valgrind development package on your build
system to provide for the core header files. For instance, such
package is called _valgrind-devel_ on Fedora.

Available real-time APIs
------------------------

[horizontal]
*Alchemy*::
		This is a re-implementation from scratch of Xenomai's
		2.x _native_ API, fully rebased on the new RTOS
		abstraction interface.

*pSOS*::
		http://www.windriver.com[pSOS (TM)] is a registered
		trademark of Wind River Systems, Inc.

*VxWorks*::
		http://www.windriver.com[VxWorks (TM)] is a registered
		trademark of Wind River Systems, Inc.
