// ** The above line should force tbl to be a preprocessor **
// Man page for latency
//
// Copyright (C) 2008 Roland Stigge <stigge@antcom.de>
//
// You may distribute under the terms of the GNU General Public
// License as specified in the file COPYING that comes with the
// Xenomai distribution.
//
//
LATENCY(1)
==========
:doctype: manpage
:revdate: 2008/04/19
:man source: Xenomai
:man version: {xenover}
:man manual: Xenomai Manual

NAME
-----
latency - Xenomai timer latency benchmark

SYNOPSIS
---------
// The general command line
*latency* [ options ]

DESCRIPTION
------------
*latency* is part of the Xenomai test suite. It is a timer latency
benchmark program.  The system must run a suitable Xenomai enabled kernel with
the respective module (xeno_timerbench).

OPTIONS
--------
*latency* accepts the following options:

*-h*::
print histograms of min, avg, max latencies

*-s*::
print statistics of min, avg, max latencies

*-H <histogram-size>*::
default = 200, increase if your last bucket is full

*-B <bucket-size>*::
default = 1000ns, decrease for more resolution

*-p <period_us>*::
sampling period

*-l <data-lines per header>*::
default=21, 0 to supress headers

*-T <test_duration_seconds>*::
default=0, so ^C to end

*-q*::
supresses RTD, RTH lines if -T is used

*-D <testing_device_no>*::
number of testing device, default=0

*-t <test_mode>*::
0=user task (default), 1=kernel task, 2=timer IRQ

*-f*::
freeze trace for each new max latency

*-c <cpu>*::
pin measuring task down to given CPU

*-P <priority>*::
task priority (test mode 0 and 1 only)

AUTHOR
-------
*latency* was written by Philippe Gerum. This man page
was written by Roland Stigge.
