EXTRA_CFLAGS += -I$(xeno_srctree)/include \
		-I$(xeno_srcdir)/.. \
		-I$(xeno_srcdir)/../../skins \
		-I$(src)/../../include \
		-I$(src)/../.. \
		-I$(xeno_srcdir) \
		$(xeno_extradef)

obj-m += $(xeno_target).o

$(xeno_target)-objs := $(xeno_objs)
