Xenomai: Semaphore Services
Semaphore Services
RTDM » Driver programming interface » Synchronisation Services
Functions
void rtdm_sem_init (rtdm_sem_t *sem, unsigned long value)
Initialise a semaphore.
void rtdm_sem_destroy (rtdm_sem_t *sem)
Destroy a semaphore.
int rtdm_sem_down (rtdm_sem_t *sem)
Decrement a semaphore.
int rtdm_sem_timeddown (rtdm_sem_t *sem, nanosecs_rel_t timeout, rtdm_toseq_t *timeout_seq)
Decrement a semaphore with timeout.
void rtdm_sem_up (rtdm_sem_t *sem)
Increment a semaphore.
int rtdm_sem_select (rtdm_sem_t *sem, rtdm_selector_t *selector, enum rtdm_selecttype type, unsigned int fd_index)
Bind a selector to a semaphore.
Detailed Description
Function Documentation
void rtdm_sem_destroy (rtdm_sem_t * sem)
Destroy a semaphore.
Parameters
[in,out] sem Semaphore handle as returned by rtdm_sem_init()
Tags
task-unrestricted, might-switch
References XNRMID, and xnselect_destroy().
int rtdm_sem_down (rtdm_sem_t * sem)
Decrement a semaphore.
This is the light-weight version of rtdm_sem_timeddown(), implying an infinite timeout.
Parameters
[in,out] sem Semaphore handle as returned by rtdm_sem_init()
Returns
0 on success, otherwise:
-EINTR is returned if calling task has been unblock by a signal or explicitly via rtdm_task_unblock().
-EIDRM is returned if sem has been destroyed.
-EPERM may be returned if an illegal invocation environment is detected.
Tags
primary-only, might-switch
References rtdm_sem_timeddown().
void rtdm_sem_init (rtdm_sem_t * sem, unsigned long value)
Initialise a semaphore.
Parameters
[in,out] sem Semaphore handle
[in] value Initial value of the semaphore
Tags
task-unrestricted
References xnselect_init(), and xnsynch_init().
int rtdm_sem_select (rtdm_sem_t * sem, rtdm_selector_t * selector, enum rtdm_selecttype type, unsigned int fd_index)
Bind a selector to a semaphore.
This functions binds the given selector to the semaphore so that the former is notified when the semaphore state changes. Typically the select binding handler will invoke this service.
Parameters
[in,out] sem Semaphore handle as returned by rtdm_sem_init()
[in,out] selector Selector as passed to the select binding handler
[in] type Type of the bound event as passed to the select binding handler
[in] fd_index File descriptor index as passed to the select binding handler
Returns
0 on success, otherwise:
-ENOMEM is returned if there is insufficient memory to establish the dynamic binding.
-EINVAL is returned if type or fd_index are invalid.
Tags
task-unrestricted
References xnselect_bind().
int rtdm_sem_timeddown (rtdm_sem_t * sem, nanosecs_rel_t timeout, rtdm_toseq_t * timeout_seq)
Decrement a semaphore with timeout.
This function tries to decrement the given semphore's value if it is positive on entry. If not, the caller is blocked unless non-blocking operation was selected.
Parameters
[in,out] sem Semaphore handle as returned by rtdm_sem_init()
[in] timeout Relative timeout in nanoseconds, see RTDM_TIMEOUT_xxx for special values
[in,out] timeout_seq Handle of a timeout sequence as returned by rtdm_toseq_init() or NULL
Returns
0 on success, otherwise:
-ETIMEDOUT is returned if the if the request has not been satisfied within the specified amount of time.
-EWOULDBLOCK is returned if timeout is negative and the semaphore value is currently not positive.
-EINTR is returned if calling task has been unblock by a signal or explicitly via rtdm_task_unblock().
-EIDRM is returned if sem has been destroyed.
-EPERM may be returned if an illegal invocation environment is detected.
Tags
primary-only, might-switch
References XNRMID, xnselect_signal(), xnsynch_sleep_on(), xnthread_current(), and XNTIMEO.
Referenced by rtdm_sem_down().
void rtdm_sem_up (rtdm_sem_t * sem)
Increment a semaphore.
This function increments the given semphore's value, waking up a potential waiter which was blocked upon rtdm_sem_down().
Parameters
[in,out] sem Semaphore handle as returned by rtdm_sem_init()
Tags
unrestricted, might-switch
References xnsched_run(), xnselect_signal(), and xnsynch_wakeup_one_sleeper().