Xenomai: Interrupt management
Interrupt management
Cobalt kernel
Functions
void xnintr_destroy (struct xnintr *intr)
Destroy an interrupt object.
int xnintr_attach (struct xnintr *intr, void *cookie)
Attach an interrupt object.
void xnintr_detach (struct xnintr *intr)
Detach an interrupt object.
void xnintr_enable (struct xnintr *intr)
Enable an interrupt object.
void xnintr_disable (struct xnintr *intr)
Disable an interrupt object.
void xnintr_affinity (struct xnintr *intr, cpumask_t cpumask)
Set interrupt's processor affinity.
int xnintr_init (struct xnintr *intr, const char *name, unsigned int irq, xnisr_t isr, xniack_t iack, int flags)
Initialize an interrupt object.
Detailed Description
Function Documentation
void xnintr_affinity (struct xnintr * intr, cpumask_t cpumask)
Set interrupt's processor affinity.
Restricts the IRQ associated with the interrupt object intr to be received only on processors which bits are set in cpumask.
Parameters
intr The descriptor address of the interrupt object which affinity is to be changed.
cpumask The new processor affinity of the interrupt object.
Note
Depending on architectures, setting more than one bit in cpumask could be meaningless.
Tags
secondary-only
int xnintr_attach (struct xnintr * intr, void * cookie)
Attach an interrupt object.
Attach an interrupt object previously initialized by xnintr_init(). After this operation is completed, all IRQs received from the corresponding interrupt channel are directed to the object's ISR.
Parameters
intr The descriptor address of the interrupt object to attach.
cookie A user-defined opaque value which is stored into the interrupt object descriptor for further retrieval by the ISR/ISR handlers.
Returns
0 is returned on success. Otherwise:
-EINVAL is returned if a low-level error occurred while attaching the interrupt.
-EBUSY is returned if the interrupt object was already attached.
Note
The caller must not hold nklock when invoking this service, this would cause deadlocks.
Tags
secondary-only
Note
Attaching an interrupt resets the tracked number of receipts to zero.
Referenced by rtdm_irq_request().
void xnintr_destroy (struct xnintr * intr)
Destroy an interrupt object.
Destroys an interrupt object previously initialized by xnintr_init(). The interrupt object is automatically detached by a call to xnintr_detach(). No more IRQs will be dispatched by this object after this service has returned.
Parameters
intr The descriptor address of the interrupt object to destroy.
Tags
secondary-only
References xnintr_detach().
void xnintr_detach (struct xnintr * intr)
Detach an interrupt object.
Detach an interrupt object previously attached by xnintr_attach(). After this operation is completed, no more IRQs are directed to the object's ISR, but the interrupt object itself remains valid. A detached interrupt object can be attached again by a subsequent call to xnintr_attach().
Parameters
intr The descriptor address of the interrupt object to detach.
Note
The caller must not hold nklock when invoking this service, this would cause deadlocks.
Tags
secondary-only
Referenced by xnintr_destroy().
void xnintr_disable (struct xnintr * intr)
Disable an interrupt object.
Disables the hardware interrupt line associated with an interrupt object. This operation invalidates further interrupt requests from the given source until the IRQ line is re-enabled anew.
Parameters
intr The descriptor address of the interrupt object to disable.
Tags
secondary-only
void xnintr_enable (struct xnintr * intr)
Enable an interrupt object.
Enables the hardware interrupt line associated with an interrupt object.
Parameters
intr The descriptor address of the interrupt object to enable.
Tags
secondary-only
Referenced by rtdm_irq_request().
int xnintr_init (struct xnintr * intr, const char * name, unsigned int irq, xnisr_t isr, xniack_t iack, int flags)
Initialize an interrupt object.
Associates an interrupt object with an IRQ line.
When an interrupt occurs on the given irq line, the ISR is fired in order to deal with the hardware event. The interrupt service code may call any non-blocking service from the nucleus.
Upon receipt of an IRQ, the ISR is immediately called on behalf of the interrupted stack context, the rescheduling procedure is locked, and the interrupt source is masked at hardware level. The status value returned by the ISR is then checked for the following values:
XN_ISR_HANDLED indicates that the interrupt request has been fulfilled by the ISR.
XN_ISR_NONE indicates the opposite to XN_ISR_HANDLED. The ISR must always return this value when it determines that the interrupt request has not been issued by the dedicated hardware device.
In addition, one of the following bits may be set by the ISR :
Warning
Use these bits with care and only when you do understand their effect on the system. The ISR is not encouraged to use these bits in case it shares the IRQ line with other ISRs in the real-time domain.
XN_ISR_NOENABLE prevents the IRQ line from being re-enabled after the ISR has returned.
XN_ISR_PROPAGATE causes the IRQ event to be propagated down the pipeline to Linux. This is the regular way to share interrupts between the nucleus and the regular Linux kernel. In effect, XN_ISR_PROPAGATE implies XN_ISR_NOENABLE since it would make no sense to re-enable the IRQ line before the Linux kernel had a chance to process the propagated interrupt.
A count of interrupt receipts is tracked into the interrupt descriptor, and reset to zero each time the interrupt object is attached. Since this count could wrap around, it should be used as an indication of interrupt activity only.
Parameters
intr The address of a interrupt object descriptor the nucleus will use to store the object-specific data. This descriptor must always be valid while the object is active therefore it must be allocated in permanent memory.
name An ASCII string standing for the symbolic name of the interrupt object or NULL.
irq The hardware interrupt channel associated with the interrupt object. This value is architecture-dependent. An interrupt object must then be attached to the hardware interrupt vector using the xnintr_attach() service for the associated IRQs to be directed to this object.
isr The address of a valid low-level interrupt service routine if this parameter is non-zero. This handler will be called each time the corresponding IRQ is delivered on behalf of an interrupt context. When called, the ISR is passed the descriptor address of the interrupt object.
iack The address of an optional interrupt acknowledge routine, aimed at replacing the default one. Only very specific situations actually require to override the default setting for this parameter, like having to acknowledge non-standard PIC hardware. iack should return a non-zero value to indicate that the interrupt has been properly acknowledged. If iack is NULL, the default routine will be used instead.
flags A set of creation flags affecting the operation. The valid flags are:
XN_ISR_SHARED enables IRQ-sharing with other interrupt objects.
XN_ISR_EDGE is an additional flag need to be set together with XN_ISR_SHARED to enable IRQ-sharing of edge-triggered interrupts.
Returns
0 is returned on success. Otherwise, -EINVAL is returned if irq is not a valid interrupt number.
Tags
secondary-only
Referenced by rtdm_irq_request().