Xenomai: Misc services
Misc services
Cobalt » Analogy framework » Driver API
Functions
unsigned long long a4l_get_time (void)
Get the absolute time in nanoseconds.
Detailed Description
Function Documentation
a4l_get_time()
unsigned long long a4l_get_time (void)
Get the absolute time in nanoseconds.
Returns
the absolute time expressed in nanoseconds
References rtdm_clock_read(), rtdm_event_clear(), rtdm_event_destroy(), rtdm_event_init(), rtdm_event_signal(), rtdm_event_timedwait(), rtdm_event_wait(), rtdm_irq_free(), rtdm_irq_get_arg, RTDM_IRQ_HANDLED, RTDM_IRQ_NONE, rtdm_irq_request(), rtdm_nrtsig_destroy(), rtdm_nrtsig_init(), and rtdm_nrtsig_pend().