Xenomai: Device Registration Services
Device Registration Services
RTDM » Driver programming interface
Data Structures
struct rtdm_fd_ops
RTDM file operation descriptor.
Macros
#define RTDM_MAX_MINOR 256
Maximum number of named devices per driver.
Functions
int rtdm_open_handler (struct rtdm_fd *fd, int oflags)
Open handler for named devices.
int rtdm_socket_handler (struct rtdm_fd *fd, int protocol)
Socket creation handler for protocol devices.
void rtdm_close_handler (struct rtdm_fd *fd)
Close handler.
int rtdm_ioctl_handler (struct rtdm_fd *fd, unsigned int request, void __user *arg)
IOCTL handler.
ssize_t rtdm_read_handler (struct rtdm_fd *fd, void __user *buf, size_t size)
Read handler.
ssize_t rtdm_write_handler (struct rtdm_fd *fd, const void __user *buf, size_t size)
Write handler.
ssize_t rtdm_recvmsg_handler (struct rtdm_fd *fd, struct user_msghdr *msg, int flags)
Receive message handler.
ssize_t rtdm_sendmsg_handler (struct rtdm_fd *fd, const struct user_msghdr *msg, int flags)
Transmit message handler.
int rtdm_select_handler (struct rtdm_fd *fd, struct xnselector *selector, unsigned int type, unsigned int index)
Select handler.
int rtdm_mmap_handler (struct rtdm_fd *fd, struct vm_area_struct *vma)
Memory mapping handler.
unsigned long rtdm_get_unmapped_area_handler (struct rtdm_fd *fd, unsigned long len, unsigned long pgoff, unsigned long flags)
Allocate mapping region in address space.
int rtdm_dev_register (struct rtdm_device *dev)
Register a RTDM device.
void rtdm_dev_unregister (struct rtdm_device *dev)
Unregister a RTDM device.
Device Flags
Static flags describing a RTDM device
#define RTDM_EXCLUSIVE 0x0001
If set, only a single instance of the device can be requested by an application.
#define RTDM_FIXED_MINOR 0x0002
Use fixed minor provided in the rtdm_device description for registering.
#define RTDM_NAMED_DEVICE 0x0010
If set, the device is addressed via a clear-text name.
#define RTDM_PROTOCOL_DEVICE 0x0020
If set, the device is addressed via a combination of protocol ID and socket type.
#define RTDM_DEVICE_TYPE_MASK 0x00F0
Mask selecting the device type.
#define RTDM_SECURE_DEVICE 0x80000000
Flag indicating a secure variant of RTDM (not supported here)
Detailed Description
Macro Definition Documentation
#define RTDM_DEVICE_TYPE_MASK 0x00F0
Mask selecting the device type.
#define RTDM_EXCLUSIVE 0x0001
If set, only a single instance of the device can be requested by an application.
#define RTDM_FIXED_MINOR 0x0002
Use fixed minor provided in the rtdm_device description for registering.
If this flag is absent, the RTDM core assigns minor numbers to devices managed by a driver in order of registration.
Referenced by rtdm_dev_register().
#define RTDM_MAX_MINOR 256
Maximum number of named devices per driver.
Referenced by rtdm_dev_register().
#define RTDM_NAMED_DEVICE 0x0010
If set, the device is addressed via a clear-text name.
Referenced by rtdm_dev_register(), rtdm_dev_unregister(), and udd_register_device().
#define RTDM_PROTOCOL_DEVICE 0x0020
If set, the device is addressed via a combination of protocol ID and socket type.
Referenced by udd_register_device().
Function Documentation
void rtdm_close_handler (struct rtdm_fd * fd)
Close handler.
Parameters
[in] fd File descriptor associated with opened device instance.
See also
close() in IEEE Std 1003.1, http://www.opengroup.org/onlinepubs/009695399
int rtdm_dev_register (struct rtdm_device * dev)
Register a RTDM device.
Registers a device in the RTDM namespace.
Parameters
[in] dev Device descriptor.
Returns
0 is returned upon success. Otherwise:
-EINVAL is returned if the descriptor contains invalid entries. RTDM_PROFILE_INFO() must appear in the list of initializers for the driver properties.
-EEXIST is returned if the specified device name of protocol ID is already in use.
-ENOMEM is returned if a memory allocation failed in the process of registering the device.
-EAGAIN is returned if no registry slot is available (check/raise CONFIG_XENO_OPT_REGISTRY_NRSLOTS).
Tags
secondary-only
References rtdm_fd_ops::close, rtdm_driver::device_count, rtdm_driver::device_flags, rtdm_device::driver, rtdm_device::label, rtdm_device::minor, rtdm_fd_ops::open, rtdm_driver::ops, rtdm_driver::protocol_family, RTDM_FIXED_MINOR, RTDM_MAX_MINOR, RTDM_NAMED_DEVICE, rtdm_fd_ops::socket, rtdm_driver::socket_type, xnregistry_enter(), and xnregistry_remove().
Referenced by udd_register_device().
void rtdm_dev_unregister (struct rtdm_device * dev)
Unregister a RTDM device.
Removes the device from the RTDM namespace. This routine waits until all connections to device have been closed prior to unregistering.
Parameters
[in] dev Device descriptor.
Tags
secondary-only
References rtdm_driver::device_flags, rtdm_device::driver, rtdm_device::minor, RTDM_NAMED_DEVICE, and xnregistry_remove().
Referenced by udd_register_device(), and udd_unregister_device().
unsigned long rtdm_get_unmapped_area_handler (struct rtdm_fd * fd, unsigned long len, unsigned long pgoff, unsigned long flags)
Allocate mapping region in address space.
When present, this optional handler should return the start address of a free region in the process's address space, large enough to cover the ongoing mmap() operation. If unspecified, the default architecture-defined handler is invoked.
Most drivers can omit this handler, except on MMU-less platforms (see second note).
Parameters
[in] fd File descriptor
[in] len Length of the requested region
[in] pgoff Page frame number to map to (see second note).
[in] flags Requested mapping flags
Returns
The start address of the mapping region on success. On failure, a negative error code should be returned, with -ENOSYS meaning that the driver does not want to provide such information, in which case the ongoing mmap() operation will fail.
Note
The address hint passed to the mmap() request is deliberately ignored by RTDM, and therefore not passed to this handler.
On MMU-less platforms, this handler is required because RTDM issues mapping requests over a shareable character device internally. In such context, the RTDM core may pass a null pgoff argument to the handler, for probing for the logical start address of the memory region to map to. Otherwise, when pgoff is non-zero, pgoff << PAGE_SHIFT is usually returned.
int rtdm_ioctl_handler (struct rtdm_fd * fd, unsigned int request, void __user * arg)
IOCTL handler.
Parameters
[in] fd File descriptor
[in] request Request number as passed by the user
[in,out] arg Request argument as passed by the user
Returns
A positive value or 0 on success. On failure return either -ENOSYS, to request that the function be called again from the opposite realtime/non-realtime context, or another negative error code.
See also
ioctl() in IEEE Std 1003.1, http://www.opengroup.org/onlinepubs/009695399
int rtdm_mmap_handler (struct rtdm_fd * fd, struct vm_area_struct * vma)
Memory mapping handler.
Parameters
[in] fd File descriptor
[in] vma Virtual memory area descriptor
Returns
0 on success. On failure, a negative error code is returned.
See also
mmap() in POSIX.1-2001, http://pubs.opengroup.org/onlinepubs/7908799/xsh/mmap.html
Note
The address hint passed to the mmap() request is deliberately ignored by RTDM.
int rtdm_open_handler (struct rtdm_fd * fd, int oflags)
Open handler for named devices.
Parameters
[in] fd File descriptor associated with opened device instance
[in] oflags Open flags as passed by the user
The file descriptor carries a device minor information which can be retrieved by a call to rtdm_fd_minor(fd). The minor number can be used for distinguishing devices managed by a driver.
Returns
0 on success. On failure, a negative error code is returned.
See also
open() in IEEE Std 1003.1, http://www.opengroup.org/onlinepubs/009695399
ssize_t rtdm_read_handler (struct rtdm_fd * fd, void __user * buf, size_t size)
Read handler.
Parameters
[in] fd File descriptor
[out] buf Input buffer as passed by the user
[in] size Number of bytes the user requests to read
Returns
On success, the number of bytes read. On failure return either -ENOSYS, to request that this handler be called again from the opposite realtime/non-realtime context, or another negative error code.
See also
read() in IEEE Std 1003.1, http://www.opengroup.org/onlinepubs/009695399
ssize_t rtdm_recvmsg_handler (struct rtdm_fd * fd, struct user_msghdr * msg, int flags)
Receive message handler.
Parameters
[in] fd File descriptor
[in,out] msg Message descriptor as passed by the user, automatically mirrored to safe kernel memory in case of user mode call
[in] flags Message flags as passed by the user
Returns
On success, the number of bytes received. On failure return either -ENOSYS, to request that this handler be called again from the opposite realtime/non-realtime context, or another negative error code.
See also
recvmsg() in IEEE Std 1003.1, http://www.opengroup.org/onlinepubs/009695399
int rtdm_select_handler (struct rtdm_fd * fd, struct xnselector * selector, unsigned int type, unsigned int index)
Select handler.
Parameters
[in] fd File descriptor
selector Pointer to the selector structure
type Type of events (XNSELECT_READ, XNSELECT_WRITE, or XNSELECT_EXCEPT)
index Index of the file descriptor
Returns
0 on success. On failure, a negative error code is returned.
See also
select() in POSIX.1-2001, http://pubs.opengroup.org/onlinepubs/007908799/xsh/select.html
ssize_t rtdm_sendmsg_handler (struct rtdm_fd * fd, const struct user_msghdr * msg, int flags)
Transmit message handler.
Parameters
[in] fd File descriptor
[in] msg Message descriptor as passed by the user, automatically mirrored to safe kernel memory in case of user mode call
[in] flags Message flags as passed by the user
Returns
On success, the number of bytes transmitted. On failure return either -ENOSYS, to request that this handler be called again from the opposite realtime/non-realtime context, or another negative error code.
See also
sendmsg() in IEEE Std 1003.1, http://www.opengroup.org/onlinepubs/009695399
int rtdm_socket_handler (struct rtdm_fd * fd, int protocol)
Socket creation handler for protocol devices.
Parameters
[in] fd File descriptor associated with opened device instance
[in] protocol Protocol number as passed by the user
Returns
0 on success. On failure, a negative error code is returned.
See also
socket() in IEEE Std 1003.1, http://www.opengroup.org/onlinepubs/009695399
ssize_t rtdm_write_handler (struct rtdm_fd * fd, const void __user * buf, size_t size)
Write handler.
Parameters
[in] fd File descriptor
[in] buf Output buffer as passed by the user
[in] size Number of bytes the user requests to write
Returns
On success, the number of bytes written. On failure return either -ENOSYS, to request that this handler be called again from the opposite realtime/non-realtime context, or another negative error code.
See also
write() in IEEE Std 1003.1, http://www.opengroup.org/onlinepubs/009695399