Xenomai: rtdm_fd_ops Struct Reference
rtdm_fd_ops Struct Reference
RTDM » Driver programming interface » Device Registration Services
RTDM file operation descriptor.
Data Fields
int(* open)(struct rtdm_fd *fd, int oflags)
See rtdm_open_handler().
int(* socket)(struct rtdm_fd *fd, int protocol)
See rtdm_socket_handler().
void(* close)(struct rtdm_fd *fd)
See rtdm_close_handler().
int(* ioctl_rt)(struct rtdm_fd *fd, unsigned int request, void __user *arg)
See rtdm_ioctl_handler().
int(* ioctl_nrt)(struct rtdm_fd *fd, unsigned int request, void __user *arg)
See rtdm_ioctl_handler().
ssize_t(* read_rt)(struct rtdm_fd *fd, void __user *buf, size_t size)
See rtdm_read_handler().
ssize_t(* read_nrt)(struct rtdm_fd *fd, void __user *buf, size_t size)
See rtdm_read_handler().
ssize_t(* write_rt)(struct rtdm_fd *fd, const void __user *buf, size_t size)
See rtdm_write_handler().
ssize_t(* write_nrt)(struct rtdm_fd *fd, const void __user *buf, size_t size)
See rtdm_write_handler().
ssize_t(* recvmsg_rt)(struct rtdm_fd *fd, struct user_msghdr *msg, int flags)
See rtdm_recvmsg_handler().
ssize_t(* recvmsg_nrt)(struct rtdm_fd *fd, struct user_msghdr *msg, int flags)
See rtdm_recvmsg_handler().
ssize_t(* sendmsg_rt)(struct rtdm_fd *fd, const struct user_msghdr *msg, int flags)
See rtdm_sendmsg_handler().
ssize_t(* sendmsg_nrt)(struct rtdm_fd *fd, const struct user_msghdr *msg, int flags)
See rtdm_sendmsg_handler().
int(* select)(struct rtdm_fd *fd, struct xnselector *selector, unsigned int type, unsigned int index)
See rtdm_select_handler().
int(* mmap)(struct rtdm_fd *fd, struct vm_area_struct *vma)
See rtdm_mmap_handler().
unsigned long(* get_unmapped_area)(struct rtdm_fd *fd, unsigned long len, unsigned long pgoff, unsigned long flags)
See rtdm_get_unmapped_area_handler().
Detailed Description
RTDM file operation descriptor.
This structure describes the operations available with a RTDM device, defining handlers for submitting I/O requests. Those handlers are implemented by RTDM device drivers.
Field Documentation
void(* rtdm_fd_ops::close) (struct rtdm_fd *fd)
See rtdm_close_handler().
Referenced by rtdm_dev_register().
unsigned long(* rtdm_fd_ops::get_unmapped_area) (struct rtdm_fd *fd, unsigned long len, unsigned long pgoff, unsigned long flags)
See rtdm_get_unmapped_area_handler().
int(* rtdm_fd_ops::ioctl_nrt) (struct rtdm_fd *fd, unsigned int request, void __user *arg)
See rtdm_ioctl_handler().
int(* rtdm_fd_ops::ioctl_rt) (struct rtdm_fd *fd, unsigned int request, void __user *arg)
See rtdm_ioctl_handler().
int(* rtdm_fd_ops::mmap) (struct rtdm_fd *fd, struct vm_area_struct *vma)
See rtdm_mmap_handler().
int(* rtdm_fd_ops::open) (struct rtdm_fd *fd, int oflags)
See rtdm_open_handler().
Referenced by rtdm_dev_register(), and udd_register_device().
ssize_t(* rtdm_fd_ops::read_nrt) (struct rtdm_fd *fd, void __user *buf, size_t size)
See rtdm_read_handler().
ssize_t(* rtdm_fd_ops::read_rt) (struct rtdm_fd *fd, void __user *buf, size_t size)
See rtdm_read_handler().
ssize_t(* rtdm_fd_ops::recvmsg_nrt) (struct rtdm_fd *fd, struct user_msghdr *msg, int flags)
See rtdm_recvmsg_handler().
ssize_t(* rtdm_fd_ops::recvmsg_rt) (struct rtdm_fd *fd, struct user_msghdr *msg, int flags)
See rtdm_recvmsg_handler().
int(* rtdm_fd_ops::select) (struct rtdm_fd *fd, struct xnselector *selector, unsigned int type, unsigned int index)
See rtdm_select_handler().
ssize_t(* rtdm_fd_ops::sendmsg_nrt) (struct rtdm_fd *fd, const struct user_msghdr *msg, int flags)
See rtdm_sendmsg_handler().
ssize_t(* rtdm_fd_ops::sendmsg_rt) (struct rtdm_fd *fd, const struct user_msghdr *msg, int flags)
See rtdm_sendmsg_handler().
int(* rtdm_fd_ops::socket) (struct rtdm_fd *fd, int protocol)
See rtdm_socket_handler().
Referenced by rtdm_dev_register().
ssize_t(* rtdm_fd_ops::write_nrt) (struct rtdm_fd *fd, const void __user *buf, size_t size)
See rtdm_write_handler().
ssize_t(* rtdm_fd_ops::write_rt) (struct rtdm_fd *fd, const void __user *buf, size_t size)
See rtdm_write_handler().
The documentation for this struct was generated from the following file:
include/cobalt/kernel/rtdm/fd.h