Xenomai: Message queues
Message queues
Cobalt/POSIX real-time API
Cobalt/POSIX message queue services.
Functions
static int mq_unlink (const char *name)
Unlink a message queue.
Detailed Description
Cobalt/POSIX message queue services.
A message queue allow exchanging data between real-time threads. For a POSIX message queue, maximum message length and maximum number of messages are fixed when it is created with mq_open().
Function Documentation
int mq_unlink (const char * name) inline static
Unlink a message queue.
This service unlinks the message queue named name. The message queue is not destroyed until all queue descriptors obtained with the mq_open() service are closed with the mq_close() service. However, after a call to this service, the unlinked queue may no longer be reached with the mq_open() service.
Parameters
name name of the message queue to be unlinked.
Return values
0 on success;
-1 with errno set if:
EPERM, the caller context is invalid;
ENAMETOOLONG, the length of the name argument exceeds 64 characters;
ENOENT, the message queue does not exist.
Valid contexts:
kernel module initialization or cleanup routine;
kernel-space cancellation cleanup routine;
user-space thread (Xenomai threads switch to secondary mode);
user-space cancellation cleanup routine.
See Also
Specification.
References xnregistry_bind(), xnregistry_lookup(), and xnregistry_unlink().