Xenomai: Sched
Sched
Files
file sched.h
Scheduler interface header.
Data Structures
struct xnsched
Scheduling information structure.
Macros
#define CREATE_TRACE_POINTS
Copyright (C) 2001-2013 Philippe Gerum rpm@x.nosp@m.enom.nosp@m.ai.or.nosp@m.g.
Functions
static int xnsched_run (void)
The rescheduling procedure.
static void xnsched_rotate (struct xnsched *sched, struct xnsched_class *sched_class, const union xnsched_policy_param *sched_param)
Rotate a scheduler runqueue.
static void xnsched_rt_init (struct xnsched *sched)
Copyright (C) 2008 Philippe Gerum rpm@x.nosp@m.enom.nosp@m.ai.or.nosp@m.g.
Detailed Description
Macro Definition Documentation
#define CREATE_TRACE_POINTS
Copyright (C) 2001-2013 Philippe Gerum rpm@x.nosp@m.enom.nosp@m.ai.or.nosp@m.g.
Xenomai is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; either version 2 of the License, or (at your option) any later version.
Xenomai is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with Xenomai; if not, write to the Free Software Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.
Function Documentation
void xnsched_rotate (struct xnsched * sched, struct xnsched_class * sched_class, const union xnsched_policy_param * sched_param) inline static
Rotate a scheduler runqueue.
The specified scheduling class is requested to rotate its runqueue for the given scheduler. Rotation is performed according to the scheduling parameter specified by sched_param.
Note
The nucleus supports round-robin scheduling for the members of the RT class.
Parameters
sched The per-CPU scheduler hosting the target scheduling class.
sched_class The scheduling class which should rotate its runqueue.
sched_param The scheduling parameter providing rotation information to the specified scheduling class.
Environments:
This service should be called from:
Kernel-based task
Interrupt service routine
User-space task (primary mode only)
Rescheduling: never.
static void xnsched_rt_init (struct xnsched * sched) static
Copyright (C) 2008 Philippe Gerum rpm@x.nosp@m.enom.nosp@m.ai.or.nosp@m.g.
Xenomai is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; either version 2 of the License, or (at your option) any later version.
Xenomai is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with Xenomai; if not, write to the Free Software Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.
References xnsched::rt.
int xnsched_run (void) inline static
The rescheduling procedure.
This is the central rescheduling routine which should be called to validate and apply changes which have previously been made to the nucleus scheduling state, such as suspending, resuming or changing the priority of threads. This call performs context switches as needed. xnsched_run() schedules out the current thread if:
the current thread is about to block.
a runnable thread from a higher priority scheduling class is waiting for the CPU.
the current thread does not lead the runnable threads from its own scheduling class (i.e. round-robin).
The Cobalt core implements a lazy rescheduling scheme so that most of the services affecting the threads state MUST be followed by a call to the rescheduling procedure for the new scheduling state to be applied.
In other words, multiple changes on the scheduler state can be done in a row, waking threads up, blocking others, without being immediately translated into the corresponding context switches. When all changes have been applied, xnsched_run() should be called for considering those changes, and possibly switching context.
As a notable exception to the previous principle however, every action which ends up suspending the current thread begets an implicit call to the rescheduling procedure on behalf of the blocking service.
Typically, self-suspension or sleeping on a synchronization object automatically leads to a call to the rescheduling procedure, therefore the caller does not need to explicitly issue xnsched_run() after such operations.
The rescheduling procedure always leads to a null-effect if it is called on behalf of an interrupt service routine. Any outstanding scheduler lock held by the outgoing thread will be restored when the thread is scheduled back in.
Calling this procedure with no applicable context switch pending is harmless and simply leads to a null-effect.
Returns
Non-zero is returned if a context switch actually happened, otherwise zero if the current thread was left running.
Remarks
Tags: none.
References xnsched::lflags, and xnsched::status.
Referenced by pthread_set_mode_np(), pthread_setschedparam_ex(), rtdm_event_signal(), rtdm_mutex_unlock(), rtdm_sem_up(), xnregistry_enter(), xnselect_bind(), xnselect_destroy(), xnthread_cancel(), xnthread_start(), and xnthread_suspend().