Xenomai: Real-time shadow services.
Real-time shadow services.
Copyright (C) 2001-2013 Philippe Gerum rpm@x.nosp@m.enom.nosp@m.ai.or.nosp@m.g.
Functions
int xnshadow_harden (void)
Migrate a Linux task to the Xenomai domain.
void xnshadow_relax (int notify, int reason)
Switch a shadow thread back to the Linux domain.
int xnshadow_map_user (struct xnthread *thread, unsigned long __user *u_window_offset)
Create a shadow thread context over a user task.
int xnshadow_map_kernel (struct xnthread *thread, struct completion *done)
Create a shadow thread context over a kernel task.
int xnshadow_register_personality (struct xnpersonality *personality)
Register a new interface personality.
void * xnshadow_get_context (unsigned int muxid)
Return the per-process data attached to the calling process.
struct xnpersonality * xnshadow_push_personality (int muxid)
Stack a new personality over the current thread.
void xnshadow_pop_personality (struct xnpersonality *prev)
Pop the topmost personality from the current thread.
Detailed Description
Copyright (C) 2001-2013 Philippe Gerum rpm@x.nosp@m.enom.nosp@m.ai.or.nosp@m.g.
Copyright (C) 2001-2013 The Xenomai project http://www.xenomai.org Copyright (C) 2006 Gilles Chanteperdrix gille.nosp@m.s.ch.nosp@m.antep.nosp@m.erdr.nosp@m.ix@xe.nosp@m.noma.nosp@m.i.org
SMP support Copyright (C) 2004 The HYADES project http://www.hyades-itea.org RTAI/fusion Copyright (C) 2004 The RTAI project http://www.rtai.org
Xenomai is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; either version 2 of the License, or (at your option) any later version.
Xenomai is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with Xenomai; if not, write to the Free Software Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.
Real-time shadow services.
Function Documentation
void* xnshadow_get_context (unsigned int muxid)
Return the per-process data attached to the calling process.
This service returns the per-process data attached to the calling process for the personality whose muxid is muxid. It must be called with nklock locked, irqs off.
See xnshadow_register_personality() documentation for information on the way to attach a per-process data to a process.
Parameters
muxid the personality muxid.
Returns
the per-process data if the current context is a user-space process;
NULL otherwise.
Remarks
Tags: atomic-entry.
int xnshadow_harden (void)
Migrate a Linux task to the Xenomai domain.
This service causes the transition of "current" from the Linux domain to Xenomai. The shadow will resume in the Xenomai domain as returning from schedule().
Remarks
Tags: secondary-only, might-switch.
References xnshadow_relax().
Referenced by xnshadow_map_kernel().
int xnshadow_map_kernel (struct xnthread * thread, struct completion * done)
Create a shadow thread context over a kernel task.
This call maps a nucleus thread to the "current" Linux task running in kernel space. The priority and scheduling class of the underlying Linux task are not affected; it is assumed that the caller did set them appropriately before issuing the shadow mapping request.
This call immediately moves the calling kernel thread to the Xenomai domain.
Parameters
thread The descriptor address of the new shadow thread to be mapped to "current". This descriptor must have been previously initialized by a call to xnthread_init().
done A completion object to be signaled when thread is fully mapped over the current Linux context, waiting for xnthread_start().
Returns
0 is returned on success. Otherwise:
-ERESTARTSYS is returned if the current Linux task has received a signal, thus preventing the final migration to the Xenomai domain (i.e. in order to process the signal in the Linux domain). This error should not be considered as fatal.
-EPERM is returned if the shadow thread has been killed before the current task had a chance to return to the caller. In such a case, the real-time mapping operation has failed globally, and no Xenomai resource remains attached to it.
-EINVAL is returned if the thread control block bears the XNUSER bit.
-EBUSY is returned if either the current Linux task or the associated shadow thread is already involved in a shadow mapping.
Remarks
Tags: secondary-only, might-switch.
References xnshadow_harden(), xnthread_resume(), and xnthread_suspend().
int xnshadow_map_user (struct xnthread * thread, unsigned long __user * u_window_offset)
Create a shadow thread context over a user task.
This call maps a nucleus thread to the "current" Linux task running in userland. The priority and scheduling class of the underlying Linux task are not affected; it is assumed that the interface library did set them appropriately before issuing the shadow mapping request.
Parameters
thread The descriptor address of the new shadow thread to be mapped to "current". This descriptor must have been previously initialized by a call to xnthread_init().
u_window_offset will receive the offset of the per-thread "u_window" structure in the process shared heap associated to thread. This structure reflects thread state information visible from userland through a shared memory window.
Returns
0 is returned on success. Otherwise:
-EINVAL is returned if the thread control block does not bear the XNUSER bit.
-EBUSY is returned if either the current Linux task or the associated shadow thread is already involved in a shadow mapping.
Remarks
Tags: secondary-only.
References xnheap_alloc(), xnthread_start(), and xnthread_suspend().
void xnshadow_pop_personality (struct xnpersonality * prev)
Pop the topmost personality from the current thread.
This service pops the topmost personality off the current thread.
Parameters
prev the previous personality which was returned by the latest call to xnshadow_push_personality() for the current thread.
Remarks
Tags: secondary-only.
struct xnpersonality* xnshadow_push_personality (int muxid)
Stack a new personality over the current thread.
This service registers the current thread as a member of the additional personality identified by muxid. If the current thread is already assigned this personality, the call returns successfully with no effect.
Parameters
muxid the identifier of the additional personality.
Returns
A handle to the previous personality. The caller should save this handle for unstacking muxid when applicable via a call to xnshadow_pop_personality().
Remarks
Tags: secondary-only.
int xnshadow_register_personality (struct xnpersonality * personality)
Register a new interface personality.
personality->ops.attach_process() is called when a user-space process binds to the personality, on behalf of one of its threads. The attach_process() handler may return:
. an opaque pointer, representing the context of the calling process for this personality;
. a NULL pointer, meaning that no per-process structure should be attached to this process for this personality;
. ERR_PTR(negative value) indicating an error, the binding process will then abort.
personality->ops.detach() is called on behalf of an exiting user-space process which has previously attached to the personality. This handler is passed a pointer to the per-process data received earlier from the ops->attach_process() handler.
Remarks
Tags: none.
void xnshadow_relax (int notify, int reason)
Switch a shadow thread back to the Linux domain.
This service yields the control of the running shadow back to Linux. This is obtained by suspending the shadow and scheduling a wake up call for the mated user task inside the Linux domain. The Linux task will resume on return from xnthread_suspend() on behalf of the root thread.
Parameters
notify A boolean flag indicating whether threads monitored from secondary mode switches should be sent a SIGDEBUG signal. For instance, some internal operations like task exit should not trigger such signal.
reason The reason to report along with the SIGDEBUG signal.
Remarks
Tags: primary-only, might-switch.
Note
"current" is valid here since the shadow runs with the properties of the Linux task.
References xnthread_suspend().
Referenced by xnshadow_harden().